version: '2.1'
services:

    storage:
        volumes:
            - ${HUMBLE_DATA:-./data}/development/mysql-data:/var/lib/mysql
            - ${HUMBLE_DATA:-./data}/development/wp-content:/var/www/html/wp-content
            - ./services/wordpress/wp-content/themes/docker:/var/www/html/wp-content/themes/docker
            - ./services/wordpress/wp-content/plugins/post-gallery-lite:/var/www/html/wp-content/plugins/post-gallery-lite
            - ./services/assets:/usr/src/app

    mysql:
        ports:
            - 3306:3306

    wordpress:
        build:
            context: ./services/wordpress/
            dockerfile: Dockerfile.development

    assets:
        image: marcopeg/node:0.1
        volumes_from:
            - storage
        environment:
            - BUILD_TARGET=/var/www/html/wp-content/themes/docker
        entrypoint:
            - npm
            - start

    pma:
        image: phpmyadmin/phpmyadmin:4.6.4-1
        links:
            - mysql:db
        ports:
            - ${PMA_PORT:-8081}:80
        environment:
            - PMA_USER=${PMA_USER:-root}
            - PMA_PASSWORD=${PMA_PASSWORD:-root}
